using System;
using Unity.Collections;
using UnityEngine;

// Auto Generated by Ambi Processor
public partial class GraphNode : MonoBehaviour
{
    private int _allIndex = -1;
    private int _enabledIndex = -1;

    // The user has to use an annotation to get this callback now
    void Awake()
    {
        AmbiGraphNodeProcessor.InstanceAwakeNotification(this);
        AmbiAwake();
    }

    void OnEnable()
    {
        AmbiGraphNodeProcessor.InstanceOnEnableNotification(this);
        AmbiOnEnable();
    }

    void OnDisable()
    {
        AmbiGraphNodeProcessor.InstanceOnDisableNotification(this);
        AmbiOnDisable();
    }

    void OnDestroy()
    {
        AmbiGraphNodeProcessor.InstanceOnDestroyNotification(this);
        AmbiOnDestroy();
    }

    // csharpier-ignore
    public static void AmbiAllocate()
    {
        NodeExtents    = new(2000, Allocator.Persistent);
        ListenerRoomID = new(Allocator.Persistent);
        IsInRooms      = new(2000, Allocator.Persistent);
    }

    // csharpier-ignore
    public static void AmbiDeallocate()
    {
        if (NodeExtents.IsCreated)       NodeExtents.Dispose();
        if (ListenerRoomID.IsCreated)    ListenerRoomID.Dispose();
        if (IsInRooms.IsCreated)         IsInRooms.Dispose();
    }

    public void LoadManagedToNative()
    {
        if (_enabledIndex == -1)
            return;

        NodeExtents[_enabledIndex] = ColliderExtents;
    }

    public void LoadNativeToManaged()
    {
        if (_enabledIndex == -1)
            return;
        
        IsInRoom = IsInRooms[_enabledIndex];
    }
}

// Auto Generated by Ambi Processor
internal class AmbiGraphNodeProcessor : MonoBehaviour
{
    static AmbiGraphNodeProcessor _instance;

    internal static void InstanceAwakeNotification(GraphNode instance)
    {
        if (_instance == null)
        {
            _instance = new();
            GraphNode.AmbiAllocate();
        }
    }

    internal static void InstanceOnEnableNotification(GraphNode instance) { }

    internal static void InstanceOnDisableNotification(GraphNode instance) { }

    internal static void InstanceOnDestroyNotification(GraphNode instance) { }

    private GraphNode[] _graphNodeReferences = Array.Empty<GraphNode>();
    private int _graphNodeAmount = 0;

    private GraphNode[] _enabledGraphNodeReferences = Array.Empty<GraphNode>();
    private int _enabledGraphNodeAmount = 0;

    // single update to reduce interop cost
    void Update()
    {
        for (var i = 0; i < _enabledGraphNodeAmount; i++)
        {
            _enabledGraphNodeReferences[i].PreBatchUpdate();
            _enabledGraphNodeReferences[i].LoadManagedToNative();
        }

        GraphNode.BatchUpdate();

        for (var i = 0; i < _enabledGraphNodeAmount; i++)
        {
            _enabledGraphNodeReferences[i].LoadNativeToManaged();
            _enabledGraphNodeReferences[i].PostBatchUpdate();
        }
    }
}
