using System;
using Unity.Collections;
using UnityEngine;

// Auto Generated by Ambi Processor
public partial class GraphNode : MonoBehaviour
{
    internal const int AmbiCapacity = 2000;

    internal int _allIndex = -1;
    internal int _enabledIndex = -1;

    void Awake()
    {
        AmbiGraphNodeProcessor.InstanceAwakeNotification(this);
        AmbiAwake();
    }

    void OnEnable()
    {
        AmbiGraphNodeProcessor.InstanceOnEnableNotification(this);
        AmbiOnEnable();
    }

    void OnDisable()
    {
        AmbiGraphNodeProcessor.InstanceOnDisableNotification(this);
        AmbiOnDisable();
    }

    void OnDestroy()
    {
        AmbiGraphNodeProcessor.InstanceOnDestroyNotification(this);
        AmbiOnDestroy();
    }

    internal static void AmbiAllocate()
    {
        NodeExtents = new(AmbiCapacity, Allocator.Persistent);
        ListenerRoomID = new(Allocator.Persistent);
        IsInRooms = new(AmbiCapacity, Allocator.Persistent);
    }

    internal static void AmbiDeallocate()
    {
        if (NodeExtents.IsCreated)
            NodeExtents.Dispose();
        if (ListenerRoomID.IsCreated)
            ListenerRoomID.Dispose();
        if (IsInRooms.IsCreated)
            IsInRooms.Dispose();
    }

    internal static void AmbiSwapBack(int destination, int source)
    {
        NodeExtents[destination] = NodeExtents[source];
        IsInRooms[destination] = IsInRooms[source];

        NodeExtents[source] = default;
        IsInRooms[source] = default;
    }

    internal static void AmbiRemoveAtSwapBack(int removedIndex, int lastIndex)
    {
        if (removedIndex != lastIndex)
        {
            NodeExtents[removedIndex] = NodeExtents[lastIndex];
            IsInRooms[removedIndex] = IsInRooms[lastIndex];
        }

        NodeExtents[lastIndex] = default;
        IsInRooms[lastIndex] = default;
    }

    internal void LoadManagedToNative()
    {
        if (_enabledIndex == -1)
            return;

        NodeExtents[_enabledIndex] = ColliderExtents;
    }

    internal void LoadNativeToManaged()
    {
        if (_enabledIndex == -1)
            return;

        IsInRoom = IsInRooms[_enabledIndex];
    }
}

// Auto Generated by Ambi Processor
internal sealed class AmbiGraphNodeProcessor : MonoBehaviour
{
    private static AmbiGraphNodeProcessor _instance;

    private GraphNode[] _graphNodeReferences;
    private GraphNode[] _enabledGraphNodeReferences;

    private int _graphNodeAmount;
    private int _enabledGraphNodeAmount;

    private static AmbiGraphNodeProcessor GetOrCreate()
    {
        if (_instance != null)
            return _instance;

        GraphNode.AmbiAllocate();

        var processorObject = new GameObject(nameof(AmbiGraphNodeProcessor)) { hideFlags = HideFlags.HideInHierarchy };

        DontDestroyOnLoad(processorObject);

        _instance = processorObject.AddComponent<AmbiGraphNodeProcessor>();
        _instance._graphNodeReferences = new GraphNode[GraphNode.AmbiCapacity];
        _instance._enabledGraphNodeReferences = new GraphNode[GraphNode.AmbiCapacity];

        return _instance;
    }

    internal static void InstanceAwakeNotification(GraphNode instance)
    {
        GetOrCreate().Register(instance);
    }

    internal static void InstanceOnEnableNotification(GraphNode instance)
    {
        var processor = GetOrCreate();
        processor.Register(instance);
        processor.RegisterEnabled(instance);
    }

    internal static void InstanceOnDisableNotification(GraphNode instance)
    {
        if (_instance != null)
            _instance.DeregisterEnabled(instance);
    }

    internal static void InstanceOnDestroyNotification(GraphNode instance)
    {
        if (_instance == null)
            return;

        var processor = _instance;

        processor.DeregisterEnabled(instance);
        processor.Deregister(instance);

        if (processor._graphNodeAmount != 0)
            return;

        _instance = null;
        GraphNode.AmbiDeallocate();
        Destroy(processor.gameObject);
    }

    private void Register(GraphNode instance)
    {
        if (instance._allIndex != -1)
            return;

        if (_graphNodeAmount == _graphNodeReferences.Length)
            throw new InvalidOperationException($"GraphNode capacity of {GraphNode.AmbiCapacity} was exceeded.");

        instance._allIndex = _graphNodeAmount;
        _graphNodeReferences[_graphNodeAmount++] = instance;
    }

    private void RegisterEnabled(GraphNode instance)
    {
        if (instance._enabledIndex != -1)
            return;

        if (_enabledGraphNodeAmount == _enabledGraphNodeReferences.Length)
            throw new InvalidOperationException($"Enabled GraphNode capacity of {GraphNode.AmbiCapacity} was exceeded.");

        instance._enabledIndex = _enabledGraphNodeAmount;
        _enabledGraphNodeReferences[_enabledGraphNodeAmount++] = instance;
        instance.LoadManagedToNative();
    }

    private void Deregister(GraphNode instance)
    {
        var removedIndex = instance._allIndex;

        if (removedIndex == -1)
            return;

        var lastIndex = --_graphNodeAmount;

        if (removedIndex != lastIndex)
        {
            var movedInstance = _graphNodeReferences[lastIndex];
            _graphNodeReferences[removedIndex] = movedInstance;
            movedInstance._allIndex = removedIndex;
        }

        _graphNodeReferences[lastIndex] = null;
        instance._allIndex = -1;
    }

    private void DeregisterEnabled(GraphNode instance)
    {
        var removedIndex = instance._enabledIndex;

        if (removedIndex == -1)
            return;

        var lastIndex = --_enabledGraphNodeAmount;

        if (removedIndex != lastIndex)
        {
            var movedInstance = _enabledGraphNodeReferences[lastIndex];

            _enabledGraphNodeReferences[removedIndex] = movedInstance;
            movedInstance._enabledIndex = removedIndex;
        }

        _enabledGraphNodeReferences[lastIndex] = null;
        instance._enabledIndex = -1;

        GraphNode.AmbiRemoveAtSwapBack(removedIndex, lastIndex);
    }

    private void Update()
    {
        for (var i = 0; i < _enabledGraphNodeAmount; i++)
        {
            var instance = _enabledGraphNodeReferences[i];
            instance.PreBatchUpdate();
            instance.LoadManagedToNative();
        }

        GraphNode.BatchUpdate();

        for (var i = 0; i < _enabledGraphNodeAmount; i++)
        {
            var instance = _enabledGraphNodeReferences[i];
            instance.LoadNativeToManaged();
            instance.PostBatchUpdate();
        }
    }

    private void OnDestroy()
    {
        if (_instance != this)
            return;

        _instance = null;
        GraphNode.AmbiDeallocate();
    }
}
