using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(WyrmAudioSettings))]
public class WyrmAudioSettingsEditor : Editor
{
    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        GUILayout.Space(20);
        
        if (GUILayout.Button("Generate C# Wyrm Mixer Class", GUILayout.Height(35)))
        {
            GenerateStaticClass();
        }
        GUI.backgroundColor = Color.white;
    }

    private void GenerateStaticClass()
    {
        WyrmAudioSettings settings = (WyrmAudioSettings)target;

        if (settings.ActiveMixerConfigs == null || settings.ActiveMixerConfigs.Count == 0)
        {
            Debug.LogWarning("WyrmAudio: No Active Mixer Configs found to generate.");
            return;
        }

        string fileName = "WyrmMixer.g.cs";
        string[] existingGuids = AssetDatabase.FindAssets("WyrmMixer.g");
        string filePath = existingGuids.Length > 0 
            ? AssetDatabase.GUIDToAssetPath(existingGuids[0]) 
            : EditorUtility.SaveFilePanelInProject("Save Generated Class", fileName, "cs", "Select save location");

        if (string.IsNullOrEmpty(filePath)) return;

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was auto-generated by WyrmAudioSettingsEditor.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.Audio;");
        sb.AppendLine();
        sb.AppendLine("public static class WyrmMixer");
        sb.AppendLine("{");

        // 1. Group active configs by Mixer Name
        var validConfigs = settings.ActiveMixerConfigs
            .Where(c => c != null && c.targetMixerGroup != null)
            .GroupBy(c => c.targetMixerGroup.audioMixer.name)
            .ToList();

        // Used to build the switch statement mapping later
        var initializationCases = new List<string>();

        // 2. Generate the nested static classes and fields
        foreach (var mixerGroup in validConfigs)
        {
            string mixerClassName = SanitizeIdentifier(mixerGroup.Key);
            sb.AppendLine($"    public static class {mixerClassName}");
            sb.AppendLine("    {");

            HashSet<string> usedNames = new HashSet<string>();

            foreach (var config in mixerGroup)
            {
                string rawGroupName = config.targetMixerGroup.name;
                string fieldName = SanitizeIdentifier(rawGroupName);
                
                // Prevent C# errors
                if (fieldName == mixerClassName) fieldName += "_Group";
                if (usedNames.Contains(fieldName)) continue; 
                usedNames.Add(fieldName);

                // Extremely fast, raw static field access
                sb.AppendLine($"        public static AudioMixerGroup {fieldName};");

                // Store string match for O(1) boot mapping
                string configId = $"{mixerGroup.Key}/{rawGroupName}";
                initializationCases.Add($"                case \"{configId}\":");
                initializationCases.Add($"                    {mixerClassName}.{fieldName} = config.targetMixerGroup;");
                initializationCases.Add($"                    break;");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // 3. Generate the boot-time initialization method
        sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("    private static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        var settings = WyrmAudioSettings.Instance;");
        sb.AppendLine("        if (settings == null) return;");
        sb.AppendLine();
        sb.AppendLine("        for (int i = 0; i < settings.ActiveMixerConfigs.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var config = settings.ActiveMixerConfigs[i];");
        sb.AppendLine("            if (config == null || config.targetMixerGroup == null) continue;");
        sb.AppendLine();
        sb.AppendLine("            string id = config.targetMixerGroup.audioMixer.name + \"/\" + config.targetMixerGroup.name;");
        sb.AppendLine("            switch (id)");
        sb.AppendLine("            {");
        
        foreach (var caseLine in initializationCases)
        {
            sb.AppendLine(caseLine);
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.ImportAsset(filePath);
        
        Debug.Log($"WyrmAudio: Generated class updated at {filePath}");
    }

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "Unknown";
        string result = Regex.Replace(name, @"[^a-zA-Z0-9_]", "");
        if (char.IsDigit(result[0])) result = "_" + result;
        return result;
    }
}