using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

public partial class WyrmAudioSettingsEditor : Editor
{
    private void GenerateStaticClass()
    {
        WyrmAudioSettings settings = (WyrmAudioSettings)target;

        if (settings.ActiveMixerConfigs == null || settings.ActiveMixerConfigs.Count == 0)
        {
            Debug.LogWarning("WyrmAudio: No Active Mixer Configs found to generate.");
            return;
        }

        string fileName = "WyrmMixer.g.cs";
        string[] existingGuids = AssetDatabase.FindAssets("WyrmMixer.g");
        string filePath = existingGuids.Length > 0
            ? AssetDatabase.GUIDToAssetPath(existingGuids[0])
            : EditorUtility.SaveFilePanelInProject("Save Generated Class", fileName, "cs", "Select save location");

        if (string.IsNullOrEmpty(filePath)) return;

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was auto-generated by WyrmAudioSettingsEditor.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.Audio;");
        sb.AppendLine();
        sb.AppendLine("public static class WyrmMixer");
        sb.AppendLine("{");

        var validConfigs = settings.ActiveMixerConfigs
            .Where(c => c != null && c.targetMixerGroup != null)
            .GroupBy(c => c.targetMixerGroup.audioMixer.name)
            .ToList();

        var initializationCases = new List<string>();

        foreach (var mixerGroup in validConfigs)
        {
            string mixerClassName = SanitizeIdentifier(mixerGroup.Key);
            sb.AppendLine($"    public static class {mixerClassName}");
            sb.AppendLine("    {");

            HashSet<string> usedNames = new HashSet<string>();

            foreach (var config in mixerGroup)
            {
                string rawGroupName = config.targetMixerGroup.name;
                string fieldName = SanitizeIdentifier(rawGroupName);

                if (fieldName == mixerClassName) fieldName += "_Group";
                if (usedNames.Contains(fieldName)) continue;
                usedNames.Add(fieldName);

                sb.AppendLine($"        public static AudioMixerGroup {fieldName};");

                string configId = $"{mixerGroup.Key}/{rawGroupName}";
                initializationCases.Add($"                case \"{configId}\":");
                initializationCases.Add($"                    {mixerClassName}.{fieldName} = config.targetMixerGroup;");
                initializationCases.Add($"                    break;");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("    private static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        var settings = WyrmAudioSettings.Instance;");
        sb.AppendLine("        if (settings == null) return;");
        sb.AppendLine();
        sb.AppendLine("        for (int i = 0; i < settings.ActiveMixerConfigs.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var config = settings.ActiveMixerConfigs[i];");
        sb.AppendLine("            if (config == null || config.targetMixerGroup == null) continue;");
        sb.AppendLine();
        sb.AppendLine("            string id = config.targetMixerGroup.audioMixer.name + \"/\" + config.targetMixerGroup.name;");
        sb.AppendLine("            switch (id)");
        sb.AppendLine("            {");

        foreach (var caseLine in initializationCases)
        {
            sb.AppendLine(caseLine);
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.ImportAsset(filePath);

        Debug.Log($"WyrmAudio: Generated Mixer class updated at {filePath}");
    }

    private void GenerateSoundBanksClass()
    {

        WyrmAudioSettings settings = (WyrmAudioSettings)target;

        // Collect valid folder paths from settings
        List<string> searchFolders = new();

        if (settings.SoundBankFolders != null && settings.SoundBankFolders.Count > 0)
        {
            foreach (var folderObj in settings.SoundBankFolders)
            {
                if (folderObj == null) continue;

                string path = AssetDatabase.GetAssetPath(folderObj);

                if (AssetDatabase.IsValidFolder(path))
                {
                    searchFolders.Add(path);
                }
                else
                {
                    Debug.LogWarning($"WyrmAudio: {path} is not a valid folder.");
                }
            }
        }

        // Fallback if nothing assigned
        if (searchFolders.Count == 0)
        {
            const string fallbackPath = "Assets/Plugins/WyrmAudio/Sound Banks";

            if (AssetDatabase.IsValidFolder(fallbackPath))
            {
                searchFolders.Add(fallbackPath);
            }
            else
            {
                Debug.LogWarning("WyrmAudio: No SoundBankFolders assigned and fallback folder missing.");
                return;
            }
        }

        // Find all banks in all folders
        string[] guids = AssetDatabase.FindAssets(
            "t:WyrmLoopableBank",
            searchFolders.ToArray()
        );

        if (guids.Length == 0)
        {
            Debug.LogWarning("WyrmAudio: No WyrmLoopableBanks found in assigned folders.");
            return;
        }

        if (guids.Length == 0)
        {
            Debug.LogWarning("WyrmAudio: No WyrmLoopableBanks found in Sound Banks folder to generate.");
            return;
        }

        settings.RegisteredSoundBanks.Clear();
        NamespaceNode rootNode = new NamespaceNode { Name = "WyrmLoopableBanks" };

        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            var bank = AssetDatabase.LoadAssetAtPath<AbstractWyrmBank>(path);
            if (bank == null) continue;

            settings.RegisteredSoundBanks.Add(bank);
            int index = settings.RegisteredSoundBanks.Count - 1;

            // Determine which root folder this asset belongs to
            string matchedRoot = searchFolders
                .FirstOrDefault(root => path.StartsWith(root));

            if (string.IsNullOrEmpty(matchedRoot))
                continue;

            string relativePath = path.Substring(matchedRoot.Length);

            if (relativePath.StartsWith("/") || relativePath.StartsWith("\\"))
                relativePath = relativePath.Substring(1);

            relativePath = relativePath.Substring(0, relativePath.LastIndexOf('.'));

            string[] parts = relativePath.Split('/', '\\');

            NamespaceNode current = rootNode;
            for (int j = 0; j < parts.Length - 1; j++)
            {
                string safePart = SanitizeIdentifier(parts[j]);
                if (!current.SubNodes.ContainsKey(safePart))
                {
                    current.SubNodes[safePart] = new NamespaceNode { Name = safePart };
                }
                current = current.SubNodes[safePart];
            }

            string bankName = SanitizeIdentifier(parts.Last());

            if (bankName == current.Name) bankName += "_Bank";

            int dupCount = 1;
            string originalBankName = bankName;
            while (current.Banks.Any(b => b.fieldName == bankName) || current.SubNodes.ContainsKey(bankName))
            {
                bankName = originalBankName + "_" + dupCount;
                dupCount++;
            }

            current.Banks.Add((bankName, index));
        }

        EditorUtility.SetDirty(settings);
        AssetDatabase.SaveAssets();

        string fileName = "WyrmBank.g.cs";
        string[] existingGuids = AssetDatabase.FindAssets("WyrmBank.g");
        string filePath = existingGuids.Length > 0
            ? AssetDatabase.GUIDToAssetPath(existingGuids[0])
            : EditorUtility.SaveFilePanelInProject("Save Generated Class", fileName, "cs", "Select save location");

        if (string.IsNullOrEmpty(filePath)) return;

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was auto-generated by WyrmAudioSettingsEditor.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public static class WyrmSound");
        sb.AppendLine("{");

        foreach (var subNode in rootNode.SubNodes.Values)
        {
            WriteNamespaceNode(sb, subNode, 1);
        }

        foreach (var bank in rootNode.Banks)
        {
            sb.AppendLine($"    public static AbstractWyrmBank {bank.fieldName};");
        }

        sb.AppendLine();
        sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("    private static void InitializeSoundBanks()");
        sb.AppendLine("    {");
        sb.AppendLine("        var settings = WyrmAudioSettings.Instance;");
        sb.AppendLine("        if (settings == null) return;");
        sb.AppendLine();
        sb.AppendLine("        var banks = settings.RegisteredSoundBanks;");
        sb.AppendLine("        if (banks == null) return;");
        sb.AppendLine();

        WriteInitializations(sb, rootNode, "", 2);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.ImportAsset(filePath);

        Debug.Log($"WyrmAudio: Generated Sound Banks class updated at {filePath}");
    }

    private void WriteNamespaceNode(StringBuilder sb, NamespaceNode node, int indentLevel)
    {
        string indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}public static class {node.Name}");
        sb.AppendLine($"{indent}{{");

        foreach (var subNode in node.SubNodes.Values)
        {
            WriteNamespaceNode(sb, subNode, indentLevel + 1);
        }

        foreach (var bank in node.Banks)
        {
            sb.AppendLine($"{indent}    public static WyrmLoopableBank {bank.fieldName};");
        }

        sb.AppendLine($"{indent}}}");
    }

    private void WriteInitializations(StringBuilder sb, NamespaceNode node, string currentPath, int indentLevel)
    {
        string indent = new string(' ', indentLevel * 4);

        foreach (var bank in node.Banks)
        {
            string fullPath = string.IsNullOrEmpty(currentPath) ? bank.fieldName : $"{currentPath}.{bank.fieldName}";
            sb.AppendLine($"{indent}if (banks.Count > {bank.index}) {fullPath} = banks[{bank.index}];");
        }

        foreach (var subNode in node.SubNodes.Values)
        {
            string nextPath = string.IsNullOrEmpty(currentPath) ? subNode.Name : $"{currentPath}.{subNode.Name}";
            WriteInitializations(sb, subNode, nextPath, indentLevel);
        }
    }

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "Unknown";
        string result = Regex.Replace(name, @"[^a-zA-Z0-9_]", "");
        if (string.IsNullOrEmpty(result)) return "Unknown";
        if (char.IsDigit(result[0])) result = "_" + result;
        return result;
    }
}