using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(WyrmAudioSettings))]
public class WyrmAudioSettingsEditor : Editor
{
    private class NamespaceNode
    {
        public string Name;
        public Dictionary<string, NamespaceNode> SubNodes = new Dictionary<string, NamespaceNode>();
        public List<(string fieldName, int index)> Banks = new List<(string fieldName, int index)>();
    }

    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        GUILayout.Space(20);
        
        if (GUILayout.Button("Generate C# Wyrm Mixer Class", GUILayout.Height(35)))
        {
            GenerateStaticClass();
        }
        
        GUILayout.Space(10);
        
        if (GUILayout.Button("Generate C# Sound Banks Class", GUILayout.Height(35)))
        {
            GenerateSoundBanksClass();
        }

        GUI.backgroundColor = Color.white;
    }

    private void GenerateStaticClass()
    {
        WyrmAudioSettings settings = (WyrmAudioSettings)target;

        if (settings.ActiveMixerConfigs == null || settings.ActiveMixerConfigs.Count == 0)
        {
            Debug.LogWarning("WyrmAudio: No Active Mixer Configs found to generate.");
            return;
        }

        string fileName = "WyrmMixer.g.cs";
        string[] existingGuids = AssetDatabase.FindAssets("WyrmMixer.g");
        string filePath = existingGuids.Length > 0 
            ? AssetDatabase.GUIDToAssetPath(existingGuids[0]) 
            : EditorUtility.SaveFilePanelInProject("Save Generated Class", fileName, "cs", "Select save location");

        if (string.IsNullOrEmpty(filePath)) return;

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was auto-generated by WyrmAudioSettingsEditor.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.Audio;");
        sb.AppendLine();
        sb.AppendLine("public static class WyrmMixer");
        sb.AppendLine("{");

        var validConfigs = settings.ActiveMixerConfigs
            .Where(c => c != null && c.targetMixerGroup != null)
            .GroupBy(c => c.targetMixerGroup.audioMixer.name)
            .ToList();

        var initializationCases = new List<string>();

        foreach (var mixerGroup in validConfigs)
        {
            string mixerClassName = SanitizeIdentifier(mixerGroup.Key);
            sb.AppendLine($"    public static class {mixerClassName}");
            sb.AppendLine("    {");

            HashSet<string> usedNames = new HashSet<string>();

            foreach (var config in mixerGroup)
            {
                string rawGroupName = config.targetMixerGroup.name;
                string fieldName = SanitizeIdentifier(rawGroupName);
                
                if (fieldName == mixerClassName) fieldName += "_Group";
                if (usedNames.Contains(fieldName)) continue; 
                usedNames.Add(fieldName);

                sb.AppendLine($"        public static AudioMixerGroup {fieldName};");

                string configId = $"{mixerGroup.Key}/{rawGroupName}";
                initializationCases.Add($"                case \"{configId}\":");
                initializationCases.Add($"                    {mixerClassName}.{fieldName} = config.targetMixerGroup;");
                initializationCases.Add($"                    break;");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("    private static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        var settings = WyrmAudioSettings.Instance;");
        sb.AppendLine("        if (settings == null) return;");
        sb.AppendLine();
        sb.AppendLine("        for (int i = 0; i < settings.ActiveMixerConfigs.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var config = settings.ActiveMixerConfigs[i];");
        sb.AppendLine("            if (config == null || config.targetMixerGroup == null) continue;");
        sb.AppendLine();
        sb.AppendLine("            string id = config.targetMixerGroup.audioMixer.name + \"/\" + config.targetMixerGroup.name;");
        sb.AppendLine("            switch (id)");
        sb.AppendLine("            {");
        
        foreach (var caseLine in initializationCases)
        {
            sb.AppendLine(caseLine);
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.ImportAsset(filePath);
        
        Debug.Log($"WyrmAudio: Generated Mixer class updated at {filePath}");
    }

    private void GenerateSoundBanksClass()
    {
        WyrmAudioSettings settings = (WyrmAudioSettings)target;

        string basePath = "Assets/Plugins/WyrmAudio/Sound Banks";
        
        if (!AssetDatabase.IsValidFolder(basePath))
        {
            Debug.LogWarning($"WyrmAudio: Sound Banks folder not found at {basePath}. Please ensure the directory exists.");
            return;
        }

        string[] guids = AssetDatabase.FindAssets("t:WyrmSoundBank", new[] { basePath });
        
        if (guids.Length == 0)
        {
            Debug.LogWarning("WyrmAudio: No WyrmSoundBanks found in Sound Banks folder to generate.");
            return;
        }

        settings.RegisteredSoundBanks.Clear();
        NamespaceNode rootNode = new NamespaceNode { Name = "WyrmSoundBanks" };

        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            var bank = AssetDatabase.LoadAssetAtPath<WyrmLoopableBank>(path);
            if (bank == null) continue;
            
            settings.RegisteredSoundBanks.Add(bank);
            int index = settings.RegisteredSoundBanks.Count - 1;

            string relativePath = path.Substring(basePath.Length);
            if (relativePath.StartsWith("/") || relativePath.StartsWith("\\")) 
                relativePath = relativePath.Substring(1);
            
            relativePath = relativePath.Substring(0, relativePath.LastIndexOf('.')); // strip extension
            
            string[] parts = relativePath.Split('/', '\\');
            
            NamespaceNode current = rootNode;
            for (int j = 0; j < parts.Length - 1; j++)
            {
                string safePart = SanitizeIdentifier(parts[j]);
                if (!current.SubNodes.ContainsKey(safePart))
                {
                    current.SubNodes[safePart] = new NamespaceNode { Name = safePart };
                }
                current = current.SubNodes[safePart];
            }
            
            string bankName = SanitizeIdentifier(parts.Last());
            
            if (bankName == current.Name) bankName += "_Bank";

            int dupCount = 1;
            string originalBankName = bankName;
            while (current.Banks.Any(b => b.fieldName == bankName) || current.SubNodes.ContainsKey(bankName))
            {
                bankName = originalBankName + "_" + dupCount;
                dupCount++;
            }
            
            current.Banks.Add((bankName, index));
        }

        EditorUtility.SetDirty(settings);
        AssetDatabase.SaveAssets();

        string fileName = "WyrmBank.g.cs";
        string[] existingGuids = AssetDatabase.FindAssets("WyrmBank.g");
        string filePath = existingGuids.Length > 0 
            ? AssetDatabase.GUIDToAssetPath(existingGuids[0]) 
            : EditorUtility.SaveFilePanelInProject("Save Generated Class", fileName, "cs", "Select save location");

        if (string.IsNullOrEmpty(filePath)) return;

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was auto-generated by WyrmAudioSettingsEditor.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public static class WyrmSound");
        sb.AppendLine("{");

        foreach (var subNode in rootNode.SubNodes.Values)
        {
            WriteNamespaceNode(sb, subNode, 1);
        }

        foreach (var bank in rootNode.Banks)
        {
            sb.AppendLine($"    public static WyrmSoundBank {bank.fieldName};");
        }

        sb.AppendLine();
        sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("    private static void InitializeSoundBanks()");
        sb.AppendLine("    {");
        sb.AppendLine("        var settings = WyrmAudioSettings.Instance;");
        sb.AppendLine("        if (settings == null) return;");
        sb.AppendLine();
        sb.AppendLine("        var banks = settings.RegisteredSoundBanks;");
        sb.AppendLine("        if (banks == null) return;");
        sb.AppendLine();

        WriteInitializations(sb, rootNode, "", 2);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.ImportAsset(filePath);
        
        Debug.Log($"WyrmAudio: Generated Sound Banks class updated at {filePath}");
    }

    private void WriteNamespaceNode(StringBuilder sb, NamespaceNode node, int indentLevel)
    {
        string indent = new string(' ', indentLevel * 4);
        
        sb.AppendLine($"{indent}public static class {node.Name}");
        sb.AppendLine($"{indent}{{");

        foreach (var subNode in node.SubNodes.Values)
        {
            WriteNamespaceNode(sb, subNode, indentLevel + 1);
        }

        foreach (var bank in node.Banks)
        {
            sb.AppendLine($"{indent}    public static WyrmSoundBank {bank.fieldName};");
        }

        sb.AppendLine($"{indent}}}");
    }

    private void WriteInitializations(StringBuilder sb, NamespaceNode node, string currentPath, int indentLevel)
    {
        string indent = new string(' ', indentLevel * 4);

        foreach (var bank in node.Banks)
        {
            string fullPath = string.IsNullOrEmpty(currentPath) ? bank.fieldName : $"{currentPath}.{bank.fieldName}";
            sb.AppendLine($"{indent}if (banks.Count > {bank.index}) {fullPath} = banks[{bank.index}];");
        }

        foreach (var subNode in node.SubNodes.Values)
        {
            string nextPath = string.IsNullOrEmpty(currentPath) ? subNode.Name : $"{currentPath}.{subNode.Name}";
            WriteInitializations(sb, subNode, nextPath, indentLevel);
        }
    }

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "Unknown";
        string result = Regex.Replace(name, @"[^a-zA-Z0-9_]", "");
        if (string.IsNullOrEmpty(result)) return "Unknown"; 
        if (char.IsDigit(result[0])) result = "_" + result;
        return result;
    }
}